frameworkVersion: '3'
service: tripbh-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'prod'}
  memorySize: 512
  timeout: 30
  architecture: x86_64
  environment:
    NODE_ENV: production
    DATABASE_URL: postgresql://tripbh_admin:5yWsRSi3oMTEOhnh9rvo@tripbh-db.c3o6mgi6ouz2.ap-south-1.rds.amazonaws.com:5432/tripbh?schema=public
    JWT_SECRET: ${env:JWT_SECRET, 'tripbh-prod-jwt-secret-change-this'}
    JWT_EXPIRES_IN: 7d
    FRONTEND_URL: https://main.dt1pxzn8p4upq.amplifyapp.com

functions:
  api:
    handler: dist/src/lambda.handler
    events:
      - httpApi:
          method: '*'
          path: '/{proxy+}'
      - httpApi:
          method: '*'
          path: /

package:
  artifact: lambda.zip
